/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTenantRouteImport } from './routes/p.$tenant'
import { Route as CTenantRouteImport } from './routes/c.$tenant'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWifiusersRouteImport } from './routes/_authenticated/wifiusers'
import { Route as AuthenticatedWifipricesRouteImport } from './routes/_authenticated/wifiprices'
import { Route as AuthenticatedVouchersRouteImport } from './routes/_authenticated/vouchers'
import { Route as AuthenticatedSmscreditRouteImport } from './routes/_authenticated/smscredit'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedRouterinfoRouteImport } from './routes/_authenticated/routerinfo'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecyclebinRouteImport } from './routes/_authenticated/recyclebin'
import { Route as AuthenticatedPrintcenterRouteImport } from './routes/_authenticated/printcenter'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMikrotiksRouteImport } from './routes/_authenticated/mikrotiks'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCaptiveRouteImport } from './routes/_authenticated/captive'
import { Route as AuthenticatedBulksmsRouteImport } from './routes/_authenticated/bulksms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicConnectRouteImport } from './routes/api/public/connect'
import { Route as ApiPublicWebhooksMpesaRouteImport } from './routes/api/public/webhooks/mpesa'
import { Route as ApiPublicWebhooksMarzpayRouteImport } from './routes/api/public/webhooks/marzpay'
import { Route as ApiPublicSessionsEventRouteImport } from './routes/api/public/sessions/event'
import { Route as ApiPublicCronVoucherExpiryRemindersRouteImport } from './routes/api/public/cron/voucher-expiry-reminders'
import { Route as ApiPublicCronPurgeVouchersRouteImport } from './routes/api/public/cron/purge-vouchers'
import { Route as ApiPublicCronProbeRoutersRouteImport } from './routes/api/public/cron/probe-routers'
import { Route as ApiPublicCronDispatchCampaignsRouteImport } from './routes/api/public/cron/dispatch-campaigns'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTenantRoute = PTenantRouteImport.update({
  id: '/p/$tenant',
  path: '/p/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const CTenantRoute = CTenantRouteImport.update({
  id: '/c/$tenant',
  path: '/c/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWifiusersRoute = AuthenticatedWifiusersRouteImport.update({
  id: '/wifiusers',
  path: '/wifiusers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWifipricesRoute = AuthenticatedWifipricesRouteImport.update({
  id: '/wifiprices',
  path: '/wifiprices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVouchersRoute = AuthenticatedVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmscreditRoute = AuthenticatedSmscreditRouteImport.update({
  id: '/smscredit',
  path: '/smscredit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRouterinfoRoute = AuthenticatedRouterinfoRouteImport.update({
  id: '/routerinfo',
  path: '/routerinfo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecyclebinRoute = AuthenticatedRecyclebinRouteImport.update({
  id: '/recyclebin',
  path: '/recyclebin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintcenterRoute =
  AuthenticatedPrintcenterRouteImport.update({
    id: '/printcenter',
    path: '/printcenter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMikrotiksRoute = AuthenticatedMikrotiksRouteImport.update({
  id: '/mikrotiks',
  path: '/mikrotiks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptiveRoute = AuthenticatedCaptiveRouteImport.update({
  id: '/captive',
  path: '/captive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulksmsRoute = AuthenticatedBulksmsRouteImport.update({
  id: '/bulksms',
  path: '/bulksms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicConnectRoute = ApiPublicConnectRouteImport.update({
  id: '/api/public/connect',
  path: '/api/public/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMpesaRoute = ApiPublicWebhooksMpesaRouteImport.update({
  id: '/api/public/webhooks/mpesa',
  path: '/api/public/webhooks/mpesa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMarzpayRoute =
  ApiPublicWebhooksMarzpayRouteImport.update({
    id: '/api/public/webhooks/marzpay',
    path: '/api/public/webhooks/marzpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSessionsEventRoute = ApiPublicSessionsEventRouteImport.update({
  id: '/api/public/sessions/event',
  path: '/api/public/sessions/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronVoucherExpiryRemindersRoute =
  ApiPublicCronVoucherExpiryRemindersRouteImport.update({
    id: '/api/public/cron/voucher-expiry-reminders',
    path: '/api/public/cron/voucher-expiry-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPurgeVouchersRoute =
  ApiPublicCronPurgeVouchersRouteImport.update({
    id: '/api/public/cron/purge-vouchers',
    path: '/api/public/cron/purge-vouchers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronProbeRoutersRoute =
  ApiPublicCronProbeRoutersRouteImport.update({
    id: '/api/public/cron/probe-routers',
    path: '/api/public/cron/probe-routers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDispatchCampaignsRoute =
  ApiPublicCronDispatchCampaignsRouteImport.update({
    id: '/api/public/cron/dispatch-campaigns',
    path: '/api/public/cron/dispatch-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bulksms': typeof AuthenticatedBulksmsRoute
  '/captive': typeof AuthenticatedCaptiveRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mikrotiks': typeof AuthenticatedMikrotiksRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/printcenter': typeof AuthenticatedPrintcenterRoute
  '/recyclebin': typeof AuthenticatedRecyclebinRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routerinfo': typeof AuthenticatedRouterinfoRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/smscredit': typeof AuthenticatedSmscreditRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/wifiprices': typeof AuthenticatedWifipricesRoute
  '/wifiusers': typeof AuthenticatedWifiusersRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/c/$tenant': typeof CTenantRoute
  '/p/$tenant': typeof PTenantRoute
  '/api/public/connect': typeof ApiPublicConnectRoute
  '/api/public/cron/dispatch-campaigns': typeof ApiPublicCronDispatchCampaignsRoute
  '/api/public/cron/probe-routers': typeof ApiPublicCronProbeRoutersRoute
  '/api/public/cron/purge-vouchers': typeof ApiPublicCronPurgeVouchersRoute
  '/api/public/cron/voucher-expiry-reminders': typeof ApiPublicCronVoucherExpiryRemindersRoute
  '/api/public/sessions/event': typeof ApiPublicSessionsEventRoute
  '/api/public/webhooks/marzpay': typeof ApiPublicWebhooksMarzpayRoute
  '/api/public/webhooks/mpesa': typeof ApiPublicWebhooksMpesaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bulksms': typeof AuthenticatedBulksmsRoute
  '/captive': typeof AuthenticatedCaptiveRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mikrotiks': typeof AuthenticatedMikrotiksRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/printcenter': typeof AuthenticatedPrintcenterRoute
  '/recyclebin': typeof AuthenticatedRecyclebinRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/routerinfo': typeof AuthenticatedRouterinfoRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/smscredit': typeof AuthenticatedSmscreditRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/wifiprices': typeof AuthenticatedWifipricesRoute
  '/wifiusers': typeof AuthenticatedWifiusersRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/c/$tenant': typeof CTenantRoute
  '/p/$tenant': typeof PTenantRoute
  '/api/public/connect': typeof ApiPublicConnectRoute
  '/api/public/cron/dispatch-campaigns': typeof ApiPublicCronDispatchCampaignsRoute
  '/api/public/cron/probe-routers': typeof ApiPublicCronProbeRoutersRoute
  '/api/public/cron/purge-vouchers': typeof ApiPublicCronPurgeVouchersRoute
  '/api/public/cron/voucher-expiry-reminders': typeof ApiPublicCronVoucherExpiryRemindersRoute
  '/api/public/sessions/event': typeof ApiPublicSessionsEventRoute
  '/api/public/webhooks/marzpay': typeof ApiPublicWebhooksMarzpayRoute
  '/api/public/webhooks/mpesa': typeof ApiPublicWebhooksMpesaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bulksms': typeof AuthenticatedBulksmsRoute
  '/_authenticated/captive': typeof AuthenticatedCaptiveRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mikrotiks': typeof AuthenticatedMikrotiksRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/printcenter': typeof AuthenticatedPrintcenterRoute
  '/_authenticated/recyclebin': typeof AuthenticatedRecyclebinRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/routerinfo': typeof AuthenticatedRouterinfoRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/smscredit': typeof AuthenticatedSmscreditRoute
  '/_authenticated/vouchers': typeof AuthenticatedVouchersRoute
  '/_authenticated/wifiprices': typeof AuthenticatedWifipricesRoute
  '/_authenticated/wifiusers': typeof AuthenticatedWifiusersRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/c/$tenant': typeof CTenantRoute
  '/p/$tenant': typeof PTenantRoute
  '/api/public/connect': typeof ApiPublicConnectRoute
  '/api/public/cron/dispatch-campaigns': typeof ApiPublicCronDispatchCampaignsRoute
  '/api/public/cron/probe-routers': typeof ApiPublicCronProbeRoutersRoute
  '/api/public/cron/purge-vouchers': typeof ApiPublicCronPurgeVouchersRoute
  '/api/public/cron/voucher-expiry-reminders': typeof ApiPublicCronVoucherExpiryRemindersRoute
  '/api/public/sessions/event': typeof ApiPublicSessionsEventRoute
  '/api/public/webhooks/marzpay': typeof ApiPublicWebhooksMarzpayRoute
  '/api/public/webhooks/mpesa': typeof ApiPublicWebhooksMpesaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/bulksms'
    | '/captive'
    | '/clients'
    | '/dashboard'
    | '/mikrotiks'
    | '/payments'
    | '/printcenter'
    | '/recyclebin'
    | '/reports'
    | '/routerinfo'
    | '/sell'
    | '/settings'
    | '/smscredit'
    | '/vouchers'
    | '/wifiprices'
    | '/wifiusers'
    | '/withdraw'
    | '/c/$tenant'
    | '/p/$tenant'
    | '/api/public/connect'
    | '/api/public/cron/dispatch-campaigns'
    | '/api/public/cron/probe-routers'
    | '/api/public/cron/purge-vouchers'
    | '/api/public/cron/voucher-expiry-reminders'
    | '/api/public/sessions/event'
    | '/api/public/webhooks/marzpay'
    | '/api/public/webhooks/mpesa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/bulksms'
    | '/captive'
    | '/clients'
    | '/dashboard'
    | '/mikrotiks'
    | '/payments'
    | '/printcenter'
    | '/recyclebin'
    | '/reports'
    | '/routerinfo'
    | '/sell'
    | '/settings'
    | '/smscredit'
    | '/vouchers'
    | '/wifiprices'
    | '/wifiusers'
    | '/withdraw'
    | '/c/$tenant'
    | '/p/$tenant'
    | '/api/public/connect'
    | '/api/public/cron/dispatch-campaigns'
    | '/api/public/cron/probe-routers'
    | '/api/public/cron/purge-vouchers'
    | '/api/public/cron/voucher-expiry-reminders'
    | '/api/public/sessions/event'
    | '/api/public/webhooks/marzpay'
    | '/api/public/webhooks/mpesa'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/bulksms'
    | '/_authenticated/captive'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/mikrotiks'
    | '/_authenticated/payments'
    | '/_authenticated/printcenter'
    | '/_authenticated/recyclebin'
    | '/_authenticated/reports'
    | '/_authenticated/routerinfo'
    | '/_authenticated/sell'
    | '/_authenticated/settings'
    | '/_authenticated/smscredit'
    | '/_authenticated/vouchers'
    | '/_authenticated/wifiprices'
    | '/_authenticated/wifiusers'
    | '/_authenticated/withdraw'
    | '/c/$tenant'
    | '/p/$tenant'
    | '/api/public/connect'
    | '/api/public/cron/dispatch-campaigns'
    | '/api/public/cron/probe-routers'
    | '/api/public/cron/purge-vouchers'
    | '/api/public/cron/voucher-expiry-reminders'
    | '/api/public/sessions/event'
    | '/api/public/webhooks/marzpay'
    | '/api/public/webhooks/mpesa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CTenantRoute: typeof CTenantRoute
  PTenantRoute: typeof PTenantRoute
  ApiPublicConnectRoute: typeof ApiPublicConnectRoute
  ApiPublicCronDispatchCampaignsRoute: typeof ApiPublicCronDispatchCampaignsRoute
  ApiPublicCronProbeRoutersRoute: typeof ApiPublicCronProbeRoutersRoute
  ApiPublicCronPurgeVouchersRoute: typeof ApiPublicCronPurgeVouchersRoute
  ApiPublicCronVoucherExpiryRemindersRoute: typeof ApiPublicCronVoucherExpiryRemindersRoute
  ApiPublicSessionsEventRoute: typeof ApiPublicSessionsEventRoute
  ApiPublicWebhooksMarzpayRoute: typeof ApiPublicWebhooksMarzpayRoute
  ApiPublicWebhooksMpesaRoute: typeof ApiPublicWebhooksMpesaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$tenant': {
      id: '/p/$tenant'
      path: '/p/$tenant'
      fullPath: '/p/$tenant'
      preLoaderRoute: typeof PTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$tenant': {
      id: '/c/$tenant'
      path: '/c/$tenant'
      fullPath: '/c/$tenant'
      preLoaderRoute: typeof CTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wifiusers': {
      id: '/_authenticated/wifiusers'
      path: '/wifiusers'
      fullPath: '/wifiusers'
      preLoaderRoute: typeof AuthenticatedWifiusersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wifiprices': {
      id: '/_authenticated/wifiprices'
      path: '/wifiprices'
      fullPath: '/wifiprices'
      preLoaderRoute: typeof AuthenticatedWifipricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers': {
      id: '/_authenticated/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AuthenticatedVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/smscredit': {
      id: '/_authenticated/smscredit'
      path: '/smscredit'
      fullPath: '/smscredit'
      preLoaderRoute: typeof AuthenticatedSmscreditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routerinfo': {
      id: '/_authenticated/routerinfo'
      path: '/routerinfo'
      fullPath: '/routerinfo'
      preLoaderRoute: typeof AuthenticatedRouterinfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recyclebin': {
      id: '/_authenticated/recyclebin'
      path: '/recyclebin'
      fullPath: '/recyclebin'
      preLoaderRoute: typeof AuthenticatedRecyclebinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/printcenter': {
      id: '/_authenticated/printcenter'
      path: '/printcenter'
      fullPath: '/printcenter'
      preLoaderRoute: typeof AuthenticatedPrintcenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mikrotiks': {
      id: '/_authenticated/mikrotiks'
      path: '/mikrotiks'
      fullPath: '/mikrotiks'
      preLoaderRoute: typeof AuthenticatedMikrotiksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/captive': {
      id: '/_authenticated/captive'
      path: '/captive'
      fullPath: '/captive'
      preLoaderRoute: typeof AuthenticatedCaptiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulksms': {
      id: '/_authenticated/bulksms'
      path: '/bulksms'
      fullPath: '/bulksms'
      preLoaderRoute: typeof AuthenticatedBulksmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/connect': {
      id: '/api/public/connect'
      path: '/api/public/connect'
      fullPath: '/api/public/connect'
      preLoaderRoute: typeof ApiPublicConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mpesa': {
      id: '/api/public/webhooks/mpesa'
      path: '/api/public/webhooks/mpesa'
      fullPath: '/api/public/webhooks/mpesa'
      preLoaderRoute: typeof ApiPublicWebhooksMpesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/marzpay': {
      id: '/api/public/webhooks/marzpay'
      path: '/api/public/webhooks/marzpay'
      fullPath: '/api/public/webhooks/marzpay'
      preLoaderRoute: typeof ApiPublicWebhooksMarzpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sessions/event': {
      id: '/api/public/sessions/event'
      path: '/api/public/sessions/event'
      fullPath: '/api/public/sessions/event'
      preLoaderRoute: typeof ApiPublicSessionsEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/voucher-expiry-reminders': {
      id: '/api/public/cron/voucher-expiry-reminders'
      path: '/api/public/cron/voucher-expiry-reminders'
      fullPath: '/api/public/cron/voucher-expiry-reminders'
      preLoaderRoute: typeof ApiPublicCronVoucherExpiryRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/purge-vouchers': {
      id: '/api/public/cron/purge-vouchers'
      path: '/api/public/cron/purge-vouchers'
      fullPath: '/api/public/cron/purge-vouchers'
      preLoaderRoute: typeof ApiPublicCronPurgeVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/probe-routers': {
      id: '/api/public/cron/probe-routers'
      path: '/api/public/cron/probe-routers'
      fullPath: '/api/public/cron/probe-routers'
      preLoaderRoute: typeof ApiPublicCronProbeRoutersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch-campaigns': {
      id: '/api/public/cron/dispatch-campaigns'
      path: '/api/public/cron/dispatch-campaigns'
      fullPath: '/api/public/cron/dispatch-campaigns'
      preLoaderRoute: typeof ApiPublicCronDispatchCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBulksmsRoute: typeof AuthenticatedBulksmsRoute
  AuthenticatedCaptiveRoute: typeof AuthenticatedCaptiveRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMikrotiksRoute: typeof AuthenticatedMikrotiksRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPrintcenterRoute: typeof AuthenticatedPrintcenterRoute
  AuthenticatedRecyclebinRoute: typeof AuthenticatedRecyclebinRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRouterinfoRoute: typeof AuthenticatedRouterinfoRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSmscreditRoute: typeof AuthenticatedSmscreditRoute
  AuthenticatedVouchersRoute: typeof AuthenticatedVouchersRoute
  AuthenticatedWifipricesRoute: typeof AuthenticatedWifipricesRoute
  AuthenticatedWifiusersRoute: typeof AuthenticatedWifiusersRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBulksmsRoute: AuthenticatedBulksmsRoute,
  AuthenticatedCaptiveRoute: AuthenticatedCaptiveRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMikrotiksRoute: AuthenticatedMikrotiksRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPrintcenterRoute: AuthenticatedPrintcenterRoute,
  AuthenticatedRecyclebinRoute: AuthenticatedRecyclebinRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRouterinfoRoute: AuthenticatedRouterinfoRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSmscreditRoute: AuthenticatedSmscreditRoute,
  AuthenticatedVouchersRoute: AuthenticatedVouchersRoute,
  AuthenticatedWifipricesRoute: AuthenticatedWifipricesRoute,
  AuthenticatedWifiusersRoute: AuthenticatedWifiusersRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CTenantRoute: CTenantRoute,
  PTenantRoute: PTenantRoute,
  ApiPublicConnectRoute: ApiPublicConnectRoute,
  ApiPublicCronDispatchCampaignsRoute: ApiPublicCronDispatchCampaignsRoute,
  ApiPublicCronProbeRoutersRoute: ApiPublicCronProbeRoutersRoute,
  ApiPublicCronPurgeVouchersRoute: ApiPublicCronPurgeVouchersRoute,
  ApiPublicCronVoucherExpiryRemindersRoute:
    ApiPublicCronVoucherExpiryRemindersRoute,
  ApiPublicSessionsEventRoute: ApiPublicSessionsEventRoute,
  ApiPublicWebhooksMarzpayRoute: ApiPublicWebhooksMarzpayRoute,
  ApiPublicWebhooksMpesaRoute: ApiPublicWebhooksMpesaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
